networks:
  kocida:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  192.168.202.64/28

services:
   kocidasrv:
      image: registry.gitlab.tcint.cz/tc/kocida/kocidasrv
      ports: ['8787:8080']
      networks: [kocida]
      deploy:
        resources:
          limits:
            #cpus: '0.001'
            memory: 300M
          reservations:
            #cpus: '0.0001'
            memory: 300M