networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  192.168.201.64/28

services:
   kocidasrv:
      image: registry.gitlab.tcint.cz/tc/kocida/kocidasrv
      ports: ['8787:8080']
