apiVersion: apps/v1
kind: Deployment
metadata:
  name: kocidasrv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kocidasrv
  template:
    metadata:
      labels:
        app: kocidasrv
    spec:
      containers:
      - name: nginx
        image: marvertin/kocidasrv
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kocidasrv
spec:
  type: LoadBalancer
  selector:
    app: kocidasrv
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080