apiVersion: apps/v1
kind: Deployment
metadata:
  name: kocidasrv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kocidasrv
  template:
    metadata:
      labels:
        app: kocidasrv
    spec:
      containers:
      - name: nginx
        image: marvertin/kocidasrv
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kocidasrv
spec:
  type: LoadBalancer
  selector:
    app: kocidasrv
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kocidafe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kocidafe
  template:
    metadata:
      labels:
        app: kocidafe
    spec:
      containers:
      - name: nginx
        image: marvertin/kocidafe
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: kocidafe
spec:
  type: LoadBalancer
  selector:
    app: kocidafe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

